version: "3.8"

services:
  ghostfolio:
    image: ghostfolio/ghostfolio:latest
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3333
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      ACCESS_TOKEN_SALT: ${ACCESS_TOKEN_SALT}
      BASE_URL: ${BASE_URL}
    depends_on:
      - db
      - redis
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3333"]
      interval: 20s
      timeout: 5s
      retries: 5

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ghostfolio
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data:









